// Package scanner enumerates the files a backup run should consider:
// either the operator's default set of well-known user folders (Desktop,
// Downloads, Documents, Pictures) or a custom list pushed from the panel.
//
// Files from a well-known folder are recorded in the manifest under that
// folder's *logical* name ("Downloads/facture.pdf"), never its physical
// location. On Windows those folders are routinely redirected to another
// drive, so the physical location is a property of one machine at one
// moment in time - useless, and actively harmful, as the thing to restore
// against. Keeping the logical name means a restore just re-resolves
// "Downloads" on the target machine (registry lookup, see the
// knownfolders package) and puts the file back in that user's real
// Downloads folder, wherever it happens to live now.
package scanner

import (
	"io/fs"
	"log"
	"os"
	"path"
	"path/filepath"
	"strings"

	"backup-agent/internal/knownfolders"
	"backup-agent/internal/userctx"
)

var defaultFolderNames = []string{"Desktop", "Downloads", "Documents", "Pictures"}

// excludedDirNames are OS-managed housekeeping directories that show up
// inside a manually-configured root (an operator pointing a whole drive
// like "E:\" at the backup) but are never worth backing up: they're
// regenerated by the OS, often SID-permission-locked in ways a normal
// backup account can't read anyway, and restoring them is meaningless -
// nothing opens a restored $RECYCLE.BIN. Matched case-insensitively since
// Windows paths are.
var excludedDirNames = map[string]bool{
	"$recycle.bin":              true,
	"system volume information": true,
	".trash":                    true,
	".trashes":                  true,
	".spotlight-v100":           true,
	".fseventsd":                true,
}

// Root is one directory to walk, plus the logical name its files should be
// recorded under. Name is one of defaultFolderNames for a well-known user
// folder - the case where the physical path must not end up in the
// manifest - and empty for an arbitrary operator-configured path, which
// has no logical identity to restore against and falls back to a
// home-relative (or, failing that, absolute) path.
type Root struct {
	Path string
	Name string
}

// DefaultRoots returns the standard per-user folders to back up, resolved
// to their real current location - which on Windows may well not be under
// the home directory at all, if the user (or their IT department) moved
// one to another drive via the folder's Properties > Location tab.
// Non-existent folders (e.g. a fresh account with no Pictures folder yet)
// are silently skipped rather than treated as an error.
func DefaultRoots() []Root {
	var roots []Root
	for _, name := range defaultFolderNames {
		p := knownfolders.Resolve(name)
		if info, err := os.Stat(p); err == nil && info.IsDir() {
			roots = append(roots, Root{Path: p, Name: name})
		}
	}
	return roots
}

// ResolveRoots turns the operator-configured path list (which may contain
// bare folder names like "Desktop", or full absolute paths for something
// like an external project folder) into roots. An empty list means "use
// the defaults".
//
// A configured entry is matched against the well-known folders both by
// name and by resolved path, so "Downloads", "C:\Users\x\Downloads" and
// "E:\Downloads" (a redirected one) all produce the same logical root -
// an operator pinning down an exact path in the panel shouldn't
// accidentally lose the folder identity that makes restores land in the
// right place.
func ResolveRoots(configured []string) []Root {
	if len(configured) == 0 {
		return DefaultRoots()
	}
	home, _ := userctx.HomeDir()
	var roots []Root
	for _, p := range configured {
		p = strings.TrimSpace(p)
		if p == "" {
			continue
		}
		if name, ok := matchKnownFolderName(p); ok {
			roots = append(roots, Root{Path: knownfolders.Resolve(name), Name: name})
			continue
		}
		abs := p
		if !filepath.IsAbs(abs) {
			abs = filepath.Join(home, abs)
		}
		abs = filepath.Clean(abs)
		roots = append(roots, Root{Path: abs, Name: matchKnownFolderPath(abs)})
	}
	return roots
}

// matchKnownFolderName recognises a bare folder name, case-insensitively
// ("downloads" -> "Downloads").
func matchKnownFolderName(s string) (string, bool) {
	for _, name := range defaultFolderNames {
		if strings.EqualFold(s, name) {
			return name, true
		}
	}
	return "", false
}

// matchKnownFolderPath returns the logical name of the well-known folder
// currently living at abs, or "" if it isn't one.
func matchKnownFolderPath(abs string) string {
	for _, name := range defaultFolderNames {
		if pathsEqual(knownfolders.Resolve(name), abs) {
			return name
		}
	}
	return ""
}

// pathsEqual compares two absolute paths. Windows paths are
// case-insensitive and both separators are legal there, so compare on a
// normalised form rather than byte-for-byte.
func pathsEqual(a, b string) bool {
	return strings.EqualFold(filepath.ToSlash(filepath.Clean(a)), filepath.ToSlash(filepath.Clean(b)))
}

type FileEntry struct {
	AbsPath string
	// RelPath is where this file is recorded in the manifest, forward-slash
	// separated: "<logical folder>/<path within it>" for a well-known
	// folder, a home-relative path otherwise, or the _outside fallback when
	// it's neither.
	RelPath string
	Size    int64
	ModTime int64 // unix seconds
}

// Walk enumerates every regular file under the given roots. Errors on
// individual entries (permission denied, a file vanishing mid-walk) are
// logged and skipped rather than aborting the whole backup - a single
// locked file should never fail an otherwise-successful run.
func Walk(roots []Root) []FileEntry {
	home, _ := userctx.HomeDir()
	seen := make(map[string]bool)
	var out []FileEntry

	for _, root := range roots {
		_ = filepath.WalkDir(root.Path, func(p string, d fs.DirEntry, err error) error {
			if err != nil {
				log.Printf("scanner: skipping %s: %v", p, err)
				return nil
			}
			if d.IsDir() {
				if excludedDirNames[strings.ToLower(d.Name())] {
					return filepath.SkipDir
				}
				return nil
			}
			if !d.Type().IsRegular() {
				return nil // skip symlinks, sockets, devices, etc.
			}
			abs, err := filepath.Abs(p)
			if err != nil {
				return nil
			}
			if seen[abs] {
				return nil // overlapping configured roots
			}
			seen[abs] = true

			info, err := d.Info()
			if err != nil {
				log.Printf("scanner: stat failed for %s: %v", p, err)
				return nil
			}

			out = append(out, FileEntry{
				AbsPath: abs,
				RelPath: relPath(root, home, abs),
				Size:    info.Size(),
				ModTime: info.ModTime().Unix(),
			})
			return nil
		})
	}
	return out
}

// CheckAccess returns the roots that exist but couldn't be listed due to a
// permission error - on macOS running as a root LaunchDaemon, this is the
// signature of a missing "Full Disk Access" grant (Desktop/Documents/
// Downloads/Pictures are TCC-protected since Catalina, and no installer
// can pre-grant that on the user's behalf).
func CheckAccess(roots []Root) []string {
	var blocked []string
	for _, root := range roots {
		if _, err := os.ReadDir(root.Path); err != nil && os.IsPermission(err) {
			blocked = append(blocked, root.Path)
		}
	}
	return blocked
}

func isOutside(rel string) bool {
	return len(rel) >= 2 && rel[0] == '.' && rel[1] == '.'
}

const outsideHomePrefix = "_outside/"

// relPath decides how a file is recorded in the manifest.
//
// A file from a well-known folder is stored under that folder's logical
// name, so its physical location never enters the manifest at all and a
// restore can re-resolve the folder on whatever machine it runs on.
//
// Otherwise it's stored relative to home. Only a file that is neither -
// an operator-configured path outside the home directory - falls back to
// the "_outside" namespace. That fallback exists because on Windows
// filepath.Rel returns an error for two paths on different volumes, so
// the naive result would be the raw absolute path itself (e.g.
// "E:\Projets\x.txt"), which at restore time gets joined onto a directory
// rather than resolved as a fresh root, producing a literal "E:" path
// segment that every Windows API rejects ("La syntaxe du nom de
// fichier... est incorrecte"). sanitizeSegment strips the colon so such a
// file still restores somewhere valid; backupjob additionally records its
// real AbsPath so restore can prefer the original location when it exists.
func relPath(root Root, home, abs string) string {
	if root.Name != "" {
		if r, err := filepath.Rel(root.Path, abs); err == nil && !isOutside(r) {
			return path.Join(root.Name, filepath.ToSlash(r))
		}
	}
	if home != "" {
		if r, err := filepath.Rel(home, abs); err == nil && !isOutside(r) {
			return filepath.ToSlash(r)
		}
	}
	return outsideHomePrefix + sanitizeSegment(filepath.ToSlash(abs))
}

// IsOutsideHome reports whether a RelPath produced by Walk is the
// _outside-namespaced fallback rather than a logical or home-relative
// path - the signal backupjob uses to also record the file's real
// original AbsPath, so restore can try putting it back where it actually
// was instead of only ever under a fallback directory.
func IsOutsideHome(relPath string) bool {
	return strings.HasPrefix(relPath, outsideHomePrefix)
}

// ResolveKnownFolders resolves every well-known folder once, up front, for
// reuse across every file in a restore. A folder whose resolution fails
// (Windows Service with nobody logged in at the console right now, a
// registry read that hiccups) is simply omitted rather than falling back
// to some other guess - see knownfolders.ResolveErr for why that matters.
//
// Resolving once and reusing it, rather than fresh per file, is itself
// part of what makes restore reliable: a Windows Service restoring many
// files at once (see restoreConcurrency in restorejob) would otherwise
// repeat an expensive WTS-token-plus-registry lookup once per file at
// concurrency - exactly the kind of repeated call under load where a
// transient OS-level failure shows up - and a fresh independent failure
// per file meant it could silently affect only some files in an
// otherwise-successful restore: correct for most files, files from that
// one folder quietly missing, on some machines and not others.
func ResolveKnownFolders() map[string]string {
	out := make(map[string]string, len(defaultFolderNames))
	for _, name := range defaultFolderNames {
		p, err := knownfolders.ResolveErr(name)
		if err != nil || p == "" || !filepath.IsAbs(p) {
			continue
		}
		// A folder that resolved into a service account's own profile is
		// a wrong answer, not a usable one: those files would be
		// invisible to the user. Dropping it here means the restore
		// treats the folder as unresolved and falls back to somewhere
		// real, instead of writing into the void.
		if knownfolders.IsServiceProfilePath(p) {
			log.Printf("scanner: dossier %q résolu dans le profil d'un compte de service (%s), ignoré", name, p)
			continue
		}
		out[name] = p
	}
	return out
}

// KnownFolderDest maps a manifest path back to an absolute destination on
// *this* machine when its first segment names a well-known user folder
// already resolved into resolved (see ResolveKnownFolders): "Downloads/
// facture.pdf" becomes this user's real Downloads folder plus
// "facture.pdf". This is what puts a restored file back where it belongs
// even if the folder has been moved to another drive since - on this
// machine or on the replacement machine the snapshot was moved to.
//
// Returns ok=false for a path that doesn't start with a known folder, or
// whose folder isn't in resolved - failing closed there (rather than
// falling back to some other guess) means the caller sees an ordinary
// "couldn't restore this file" instead of a restore that reports success
// while the file vanishes into a directory the user can't see.
func KnownFolderDest(resolved map[string]string, manifestPath string) (string, bool) {
	clean := path.Clean(filepath.ToSlash(manifestPath))
	first, rest, _ := strings.Cut(clean, "/")
	dir, ok := resolved[first]
	if !ok {
		return "", false
	}
	if rest == "" {
		return dir, true
	}
	// filepath.Join cleans the remainder, so a "../" smuggled into a
	// manifest can't climb out of the resolved folder.
	dest := filepath.Join(dir, filepath.FromSlash(rest))
	if !within(dir, dest) {
		return "", false
	}
	return dest, true
}

// within reports whether dest stays inside dir.
func within(dir, dest string) bool {
	rel, err := filepath.Rel(dir, dest)
	return err == nil && !isOutside(rel)
}

// sanitizeSegment strips characters that are illegal inside a path
// component on any of our target platforms - just the Windows
// drive-letter colon in practice, since that's the only one a real
// absolute path contains before this function ever sees it.
func sanitizeSegment(p string) string {
	return strings.TrimLeft(strings.ReplaceAll(p, ":", ""), "/")
}
