// Package scanner enumerates the files a backup run should consider:
// either the operator's default set of well-known user folders (Desktop,
// Downloads, Documents, Pictures - present under the user's home directory
// on Windows, macOS and Linux alike) or a custom list pushed from the
// panel.
package scanner

import (
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"strings"

	"backup-agent/internal/knownfolders"
	"backup-agent/internal/userctx"
)

var defaultFolderNames = []string{"Desktop", "Downloads", "Documents", "Pictures"}

// excludedDirNames are OS-managed housekeeping directories that show up
// inside a manually-configured root (an operator pointing a whole drive
// like "E:\" at the backup) but are never worth backing up: they're
// regenerated by the OS, often SID-permission-locked in ways a normal
// backup account can't read anyway, and restoring them is meaningless -
// nothing opens a restored $RECYCLE.BIN. Matched case-insensitively since
// Windows paths are.
var excludedDirNames = map[string]bool{
	"$recycle.bin":              true,
	"system volume information": true,
	".trash":                    true,
	".trashes":                  true,
	".spotlight-v100":           true,
	".fseventsd":                true,
}

// DefaultRoots returns the standard per-user folders to back up, resolved
// to their real current location - which on Windows may well not be under
// the home directory at all, if the user (or their IT department) moved
// one to another drive via the folder's Properties > Location tab.
// Non-existent folders (e.g. a fresh account with no Pictures folder yet)
// are silently skipped rather than treated as an error.
func DefaultRoots() []string {
	var roots []string
	for _, name := range defaultFolderNames {
		p := knownfolders.Resolve(name)
		if info, err := os.Stat(p); err == nil && info.IsDir() {
			roots = append(roots, p)
		}
	}
	return roots
}

// ResolveRoots turns the operator-configured path list (which may contain
// bare folder names like "Desktop" relative to the home directory, or full
// absolute paths for something like an external project folder) into
// absolute paths. An empty list means "use the defaults".
func ResolveRoots(configured []string) []string {
	if len(configured) == 0 {
		return DefaultRoots()
	}
	home, _ := userctx.HomeDir()
	var roots []string
	for _, p := range configured {
		if filepath.IsAbs(p) {
			roots = append(roots, filepath.Clean(p))
			continue
		}
		roots = append(roots, filepath.Join(home, p))
	}
	return roots
}

type FileEntry struct {
	AbsPath string
	RelPath string // relative to the user's home directory, forward-slash separated
	Size    int64
	ModTime int64 // unix seconds
}

// Walk enumerates every regular file under the given roots. Errors on
// individual entries (permission denied, a file vanishing mid-walk) are
// logged and skipped rather than aborting the whole backup - a single
// locked file should never fail an otherwise-successful run.
func Walk(roots []string) []FileEntry {
	home, _ := userctx.HomeDir()
	seen := make(map[string]bool)
	var out []FileEntry

	for _, root := range roots {
		_ = filepath.WalkDir(root, func(p string, d fs.DirEntry, err error) error {
			if err != nil {
				log.Printf("scanner: skipping %s: %v", p, err)
				return nil
			}
			if d.IsDir() {
				if excludedDirNames[strings.ToLower(d.Name())] {
					return filepath.SkipDir
				}
				return nil
			}
			if !d.Type().IsRegular() {
				return nil // skip symlinks, sockets, devices, etc.
			}
			abs, err := filepath.Abs(p)
			if err != nil {
				return nil
			}
			if seen[abs] {
				return nil // overlapping configured roots
			}
			seen[abs] = true

			info, err := d.Info()
			if err != nil {
				log.Printf("scanner: stat failed for %s: %v", p, err)
				return nil
			}

			out = append(out, FileEntry{
				AbsPath: abs,
				RelPath: relPath(home, abs),
				Size:    info.Size(),
				ModTime: info.ModTime().Unix(),
			})
			return nil
		})
	}
	return out
}

// CheckAccess returns the roots that exist but couldn't be listed due to a
// permission error - on macOS running as a root LaunchDaemon, this is the
// signature of a missing "Full Disk Access" grant (Desktop/Documents/
// Downloads/Pictures are TCC-protected since Catalina, and no installer
// can pre-grant that on the user's behalf).
func CheckAccess(roots []string) []string {
	var blocked []string
	for _, root := range roots {
		if _, err := os.ReadDir(root); err != nil && os.IsPermission(err) {
			blocked = append(blocked, root)
		}
	}
	return blocked
}

func isOutside(rel string) bool {
	return len(rel) >= 2 && rel[0] == '.' && rel[1] == '.'
}

// relPath turns an absolute file path into the path stored in the
// manifest and later used to reconstruct the file on restore. When abs is
// under home this is the ordinary relative path; anything else - a
// manually configured root on a different Windows drive than home, or any
// other absolute path filepath.Rel can't relate to home - is namespaced
// under "_outside" instead of leaking the raw absolute path.
//
// Leaking it is not just untidy: on Windows filepath.Rel returns an error
// for two paths on different volumes, so the naive fallback used to be the
// raw absolute path itself (e.g. "E:\$RECYCLE.BIN\...\desktop.ini"). At
// restore time that gets joined onto the home directory - not resolved as
// a fresh root, just string-glued - producing a literal "E:" path segment,
// which every Windows API refused to create ("La syntaxe du nom de
// fichier... est incorrecte"). sanitizeSegment strips the colon so the
// exact same file still restores, just under a folder named "E" instead of
// pretending to be a second drive letter mid-path.
func relPath(home, abs string) string {
	if home != "" {
		if r, err := filepath.Rel(home, abs); err == nil && !isOutside(r) {
			return filepath.ToSlash(r)
		}
	}
	return "_outside/" + sanitizeSegment(filepath.ToSlash(abs))
}

// sanitizeSegment strips characters that are illegal inside a path
// component on any of our target platforms - just the Windows
// drive-letter colon in practice, since that's the only one a real
// absolute path contains before this function ever sees it.
func sanitizeSegment(p string) string {
	return strings.TrimLeft(strings.ReplaceAll(p, ":", ""), "/")
}
