// Package scanner enumerates the files a backup run should consider:
// either the operator's default set of well-known user folders (Desktop,
// Downloads, Documents, Pictures) or a custom list pushed from the panel.
//
// Files from a well-known folder are announced under that folder's
// *logical* name ("Downloads/facture.pdf"), never its physical location,
// and that is the path they get on the NAS. On Windows those folders are
// routinely redirected to another drive, so the physical location is a
// property of one machine at one moment in time: naming the backup after
// it would put "E/Downloads" on the NAS this month and "C/Users/x/
// Downloads" the next, splitting one folder's history in two. The logical
// name keeps the machine's tree on the NAS stable and readable - open the
// PC's folder, open Downloads, the files are there.
package scanner

import (
	"io/fs"
	"log"
	"os"
	"path"
	"path/filepath"
	"strings"

	"backup-agent/internal/knownfolders"
	"backup-agent/internal/userctx"
)

var defaultFolderNames = []string{"Desktop", "Downloads", "Documents", "Pictures"}

// excludedDirNames are OS-managed housekeeping directories that show up
// inside a manually-configured root (an operator pointing a whole drive
// like "E:\" at the backup) but are never worth backing up: they're
// regenerated by the OS, often SID-permission-locked in ways a normal
// backup account can't read anyway, and restoring them is meaningless -
// nothing opens a restored $RECYCLE.BIN. Matched case-insensitively since
// Windows paths are.
var excludedDirNames = map[string]bool{
	"$recycle.bin":              true,
	"system volume information": true,
	".trash":                    true,
	".trashes":                  true,
	".spotlight-v100":           true,
	".fseventsd":                true,
}

// Root is one directory to walk, plus the logical name its files should be
// stored under on the NAS. Name is one of defaultFolderNames for a
// well-known user folder - the case where the physical path must not end
// up in the stored tree - and empty for an arbitrary operator-configured
// path, which has no logical identity and falls back to a home-relative
// (or, failing that, absolute) path.
type Root struct {
	Path string
	Name string
}

// DefaultRoots returns the standard per-user folders to back up, resolved
// to their real current location - which on Windows may well not be under
// the home directory at all, if the user (or their IT department) moved
// one to another drive via the folder's Properties > Location tab.
// Non-existent folders (e.g. a fresh account with no Pictures folder yet)
// are silently skipped rather than treated as an error.
func DefaultRoots() []Root {
	var roots []Root
	for _, name := range defaultFolderNames {
		p := knownfolders.Resolve(name)
		if info, err := os.Stat(p); err == nil && info.IsDir() {
			roots = append(roots, Root{Path: p, Name: name})
		}
	}
	return roots
}

// ResolveRoots turns the operator-configured path list (which may contain
// bare folder names like "Desktop", or full absolute paths for something
// like an external project folder) into roots. An empty list means "use
// the defaults".
//
// A configured entry is matched against the well-known folders both by
// name and by resolved path, so "Downloads", "C:\Users\x\Downloads" and
// "E:\Downloads" (a redirected one) all produce the same logical root -
// an operator pinning down an exact path in the panel shouldn't
// accidentally lose the folder identity that makes restores land in the
// right place.
func ResolveRoots(configured []string) []Root {
	if len(configured) == 0 {
		return DefaultRoots()
	}
	home, _ := userctx.HomeDir()
	var roots []Root
	for _, p := range configured {
		p = strings.TrimSpace(p)
		if p == "" {
			continue
		}
		if name, ok := matchKnownFolderName(p); ok {
			roots = append(roots, Root{Path: knownfolders.Resolve(name), Name: name})
			continue
		}
		abs := p
		if !filepath.IsAbs(abs) {
			abs = filepath.Join(home, abs)
		}
		abs = filepath.Clean(abs)
		roots = append(roots, Root{Path: abs, Name: matchKnownFolderPath(abs)})
	}
	return roots
}

// matchKnownFolderName recognises a bare folder name, case-insensitively
// ("downloads" -> "Downloads").
func matchKnownFolderName(s string) (string, bool) {
	for _, name := range defaultFolderNames {
		if strings.EqualFold(s, name) {
			return name, true
		}
	}
	return "", false
}

// matchKnownFolderPath returns the logical name of the well-known folder
// currently living at abs, or "" if it isn't one.
func matchKnownFolderPath(abs string) string {
	for _, name := range defaultFolderNames {
		if pathsEqual(knownfolders.Resolve(name), abs) {
			return name
		}
	}
	return ""
}

// pathsEqual compares two absolute paths. Windows paths are
// case-insensitive and both separators are legal there, so compare on a
// normalised form rather than byte-for-byte.
func pathsEqual(a, b string) bool {
	return strings.EqualFold(filepath.ToSlash(filepath.Clean(a)), filepath.ToSlash(filepath.Clean(b)))
}

type FileEntry struct {
	AbsPath string
	// RelPath is where this file lands inside the machine's folder on the
	// NAS, forward-slash separated: "<logical folder>/<path within it>"
	// for a well-known folder, a home-relative path otherwise, or the
	// _outside fallback when it's neither.
	RelPath string
	Size    int64
	ModTime int64 // nanoseconds since epoch, at whatever precision the local filesystem gives
}

// Walk enumerates every regular file under the given roots. Errors on
// individual entries (permission denied, a file vanishing mid-walk) are
// logged and skipped rather than aborting the whole backup - a single
// locked file should never fail an otherwise-successful run.
func Walk(roots []Root) []FileEntry {
	home, _ := userctx.HomeDir()
	seen := make(map[string]bool)
	var out []FileEntry

	for _, root := range roots {
		// filepath.WalkDir lstats the root itself: if root.Path is a
		// symlink (not one it encounters mid-walk, which it deliberately
		// never follows - that part is correct and stays that way), the
		// DirEntry it gets back reports a symlink, not a directory, and the
		// loop below skips it as "not a regular file" - silently walking
		// zero files, no error anywhere. This is a real, common case on
		// macOS: enabling iCloud Drive's "Desktop & Documents Folders" sync
		// replaces ~/Desktop and ~/Documents with symlinks into
		// ~/Library/Mobile Documents/..., so a machine that was backing up
		// tens of GB can silently drop to whatever's left in the untouched
		// folders the moment that setting gets turned on. Resolving the
		// root to its real target before walking - but keeping root.Name
		// for the logical NAS path - fixes the walk without touching the
		// "don't follow symlinks found during the walk" behaviour at all.
		walkRoot := root
		if resolved, err := filepath.EvalSymlinks(root.Path); err == nil {
			walkRoot.Path = resolved
		}
		_ = filepath.WalkDir(walkRoot.Path, func(p string, d fs.DirEntry, err error) error {
			if err != nil {
				log.Printf("scanner: skipping %s: %v", p, err)
				return nil
			}
			if d.IsDir() {
				if excludedDirNames[strings.ToLower(d.Name())] {
					return filepath.SkipDir
				}
				return nil
			}
			if !d.Type().IsRegular() {
				return nil // skip symlinks, sockets, devices, etc.
			}
			abs, err := filepath.Abs(p)
			if err != nil {
				return nil
			}
			if seen[abs] {
				return nil // overlapping configured roots
			}
			seen[abs] = true

			info, err := d.Info()
			if err != nil {
				log.Printf("scanner: stat failed for %s: %v", p, err)
				return nil
			}

			out = append(out, FileEntry{
				AbsPath: abs,
				RelPath: relPath(walkRoot, home, abs),
				Size:    info.Size(),
				ModTime: info.ModTime().UnixNano(),
			})
			return nil
		})
	}
	return out
}

// CheckAccess returns the roots that exist but couldn't be listed due to a
// permission error - on macOS running as a root LaunchDaemon, this is the
// signature of a missing "Full Disk Access" grant (Desktop/Documents/
// Downloads/Pictures are TCC-protected since Catalina, and no installer
// can pre-grant that on the user's behalf).
func CheckAccess(roots []Root) []string {
	var blocked []string
	for _, root := range roots {
		if _, err := os.ReadDir(root.Path); err != nil && os.IsPermission(err) {
			blocked = append(blocked, root.Path)
		}
	}
	return blocked
}

func isOutside(rel string) bool {
	return len(rel) >= 2 && rel[0] == '.' && rel[1] == '.'
}

const outsideHomePrefix = "_outside/"

// relPath decides where a file lands inside the machine's folder on the
// NAS.
//
// A file from a well-known folder is stored under that folder's logical
// name, so its physical location never enters the stored tree and the
// folder keeps one stable home on the NAS even if it's moved to another
// drive on the PC.
//
// Otherwise it's stored relative to home. Only a file that is neither -
// an operator-configured path outside the home directory - falls back to
// the "_outside" namespace. That fallback exists because on Windows
// filepath.Rel returns an error for two paths on different volumes, so
// the naive result would be the raw absolute path itself (e.g.
// "E:\Projets\x.txt"), which gets joined onto the machine's folder on the
// server rather than resolved as a fresh root, producing a literal "E:"
// path segment that every Windows API rejects ("La syntaxe du nom de
// fichier... est incorrecte"). sanitizeSegment strips the colon so the
// file lands under a plain "_outside/E/Projets/x.txt" on the NAS, which an
// operator can read and copy back like anything else.
func relPath(root Root, home, abs string) string {
	if root.Name != "" {
		if r, err := filepath.Rel(root.Path, abs); err == nil && !isOutside(r) {
			return path.Join(root.Name, filepath.ToSlash(r))
		}
	}
	if home != "" {
		if r, err := filepath.Rel(home, abs); err == nil && !isOutside(r) {
			return filepath.ToSlash(r)
		}
	}
	return outsideHomePrefix + sanitizeSegment(filepath.ToSlash(abs))
}

// sanitizeSegment strips characters that are illegal inside a path
// component on any of our target platforms - just the Windows
// drive-letter colon in practice, since that's the only one a real
// absolute path contains before this function ever sees it.
func sanitizeSegment(p string) string {
	return strings.TrimLeft(strings.ReplaceAll(p, ":", ""), "/")
}
